# Generated by Django 3.0.5 on 2020-04-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso4217_code', models.CharField(max_length=3)),
                ('dkk_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'ordering': ('iso4217_code',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_native', models.DecimalField(decimal_places=2, editable=False, max_digits=20)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddyledger.Currency')),
            ],
            options={
                'ordering': ('date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('closed', models.BooleanField(default=False, editable=False)),
                ('calcmethod', models.CharField(default='basic', editable=False, max_length=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buddyledger.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ledger', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='buddyledger.Ledger')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ExpensePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haspaid', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('haspaid_native', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('shouldpay', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('shouldpay_native', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('autoamount', models.BooleanField(default=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenseparts', to='buddyledger.Expense')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buddyledger.Person')),
            ],
            options={
                'unique_together': {('expense', 'person')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='ledger',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='buddyledger.Ledger'),
        ),
        migrations.AddField(
            model_name='expense',
            name='people',
            field=models.ManyToManyField(through='buddyledger.ExpensePart', to='buddyledger.Person'),
        ),
    ]
